### ISSUE TITLE
Issue running application

### ISSUE THREAD

**Issue by creaturenex** [jinwoov/hacktoberfest#131]
Hello Jin

First of all thanks for doing this, I really appreciate it as I am learning online to become a fullstack engineer. I am currently running into an issue. I installed node, running unbuntu based machine(elementary os). When I run the following code I get this error and I am not sure how to solve it.
```
# within 
node index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/oscar/Hacktoberfest 2020/hacktoberfest/Application/index.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by creaturenex** [comment]
disregard #within, just wanted to saying I was tring to start the application from within the application folder.

**Comment by jinwoov** [comment]
you have to first run `npm i` which will install all of the dependencies
